export type Theme = {
  profile: string,
  body: string,
  text: string,
  toggleBorder: string,
  filterBackground: string,
  filterDropdown: string,
  filterOptionActive: string,
  toggleButtonBackground: string;
  button: string,
  buttonBorder: string,
  buttonBorderActive: string,
  buttonTint: string,
  cardBackground: string,
  cardTint: string,
  labelBackground: string,
  labelTint: string,
}

export const lightTheme: Theme = {
  profile: '#EEE',
  body: '#FFF',
  text: '#363537',
  filterBackground: '#DDD',
  filterDropdown: '#FFF',
  filterOptionActive: '#EEE',
  toggleBorder: '#FFF',
  toggleButtonBackground: '#999',
  // button: 'linear-gradient(#39598A, #79D7ED)',
  button: '#424282',
  buttonBorder: '#363537',
  buttonBorderActive: '#161517',
  buttonTint: '#FAFAFA',
  cardBackground: '#EEE',
  cardTint: '#363537',
  labelBackground: '#FFF',
  labelTint: '#363537',
}

export const darkTheme: Theme = {
  profile: '#262527',
  body: '#363537',
  text: '#FAFAFA',
  filterBackground: '#161517',
  filterDropdown: '#363537',
  filterOptionActive: '#262527',
  toggleBorder: '#6B8096',
  toggleButtonBackground: '#363537',
  // button: 'linear-gradient(#091236, #1E215D)',
  button: '#424282',
  buttonBorder: '#CCC',
  buttonBorderActive: '#FAFAFA',
  buttonTint: '#FAFAFA',
  cardBackground: '#262527',
  cardTint: '#FAFAFA',
  labelBackground: '#363537',
  labelTint: '#FAFAFA',
}