const Colors = {
  backgroundDark: '#212022',
  secondaryBackgroundDark: '#161517',
  backgroundLight: '#FFF',
  secondaryBackgroundLight: '#DDD',
  action: '#6F652C',
  primaryDark: '#28315e',
  primaryLight: '#3a4373',
  secondaryDark: '#353535',
  secondaryLight: '#C1C1C1',
  textDark: '#FAFAFA',
  textLight: '#363537',
}

export type Theme = {
  profile: string,
  profileTint: string,
  body: string,
  text: string,
  toggleBorder: string,
  filterBackground: string,
  filterDropdown: string,
  filterOptionActive: string,
  toggleButtonBackground: string;
  button: string,
  buttonBorder: string,
  buttonBorderActive: string,
  buttonTint: string,
  cardBackground: string,
  cardBody: string,
  cardTint: string,
  labelBackground: string,
  labelTint: string,
}

export const lightTheme: Theme = {
  profile: Colors.primaryLight,
  profileTint: Colors.textDark,
  body: Colors.backgroundLight,
  text: Colors.textLight,
  filterBackground: Colors.secondaryBackgroundLight,
  filterDropdown: Colors.backgroundLight,
  filterOptionActive: Colors.secondaryLight,
  toggleBorder: Colors.secondaryLight,
  toggleButtonBackground: '#999',
  // button: 'linear-gradient(#39598A, #79D7ED)',
  button: Colors.action,
  buttonBorder: Colors.textLight,
  buttonBorderActive: '#161517',
  buttonTint: '#FAFAFA',
  cardBackground: Colors.secondaryLight,
  cardBody: Colors.secondaryBackgroundLight,
  cardTint: Colors.textLight,
  labelBackground: Colors.secondaryLight,
  labelTint: Colors.textLight,
}

export const darkTheme: Theme = {
  profile: Colors.primaryDark,
  profileTint: Colors.textDark,
  body: Colors.backgroundDark,
  text: Colors.textDark,
  filterBackground: Colors.secondaryBackgroundDark,
  filterDropdown: Colors.backgroundDark,
  filterOptionActive: Colors.secondaryDark,
  toggleBorder: '#6B8096',
  toggleButtonBackground: Colors.primaryDark,
  // button: 'linear-gradient(#091236, #1E215D)',
  button:  Colors.action,
  buttonBorder: '#CCC',
  buttonBorderActive: Colors.textDark,
  buttonTint: Colors.textDark,
  cardBackground: Colors.secondaryDark,
  cardBody: Colors.secondaryBackgroundDark,
  cardTint: Colors.textDark,
  labelBackground: Colors.primaryDark,
  labelTint: Colors.textDark,
}